# Generated by Django 5.0.6 on 2024-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='detail_image2',
            field=models.ImageField(blank=True, upload_to='detail'),
        ),
        migrations.AddField(
            model_name='topic',
            name='detail_image3',
            field=models.ImageField(blank=True, upload_to='detail'),
        ),
    ]
