# Generated by Django 5.0.6 on 2024-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donates', '0002_topic_detail_image2_topic_detail_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='detail2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='detail3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='apr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='aug',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='dec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='feb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='jan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='jul',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='jun',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='mar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='may',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='nov',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='oct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydonations',
            name='sep',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
